### ISSUE TITLE
SynthEBD keeps crashing

### ISSUE THREAD

**Issue by greengrill** [Synthesis-Collective/SynthEBD#103]
I'm not sure if it's something on my end but I keep getting this every time I tried to run the patcher:
SynthEBD has crashed with the following error:
An object implementing IHandleObservableErrors (often a ReactiveCommand or ObservableAsPropertyHelper) has errored, thereby breaking its observable pipeline. To prevent this, ensure the pipeline does not error, or Subscribe to the ThrownExceptions property of the object in question to handle the erroneous case.
   at ReactiveUI.RxApp.<>c__DisplayClass9_0.<.cctor>b__2() in /_/src/ReactiveUI/RxApp.cs:line 109
   at System.Reactive.Concurrency.Scheduler.Invoke(Action action) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 253
   at System.Reactive.Concurrency.Scheduler.<>c.<Schedule>b__74_0(IScheduler _, Action a) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 37
   at System.Reactive.Concurrency.DispatcherScheduler.<>c__DisplayClass12_0`1.<Schedule>b__0() in /_/src/ReactiveUI.Uwp/Rx/Concurrency/DispatcherScheduler.cs:line 98
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Object reference not set to an instance of an object.
   at SynthEBD.AssetSelector.RecordMixInAssetConsistencyAndLinkedNPCs(SubgroupCombination assignedCombination, NPCInfo npcInfo, String mixInName, Boolean declinedViaProbability) in D:\a\SynthEBD\SynthEBD\SynthEBD\Patcher\Asset Patching\AssetSelector.cs:line 1067
   at SynthEBD.Patcher.MainLoop(IEnumerable`1 npcCollection, Boolean skipLinkedSecondaryNPCs, ISkyrimMod outputMod, CategorizedFlattenedAssetPacks sortedAssetPacks, BodyGenConfigs bodyGenConfigs, Settings_OBody oBodySettings, HeightConfig currentHeightConfig, Settings_Headparts headPartSettings, HashSet`1 generatedLinkGroups, HashSet`1 skippedLinkedNPCs, Keyword synthEBDFaceKW, Keyword EBDFaceKW, Keyword EBDScriptKW, FacePartCompliance facePartComplianceMaintainer, HashSet`1 headPartNPCs) in D:\a\SynthEBD\SynthEBD\SynthEBD\Patcher\Patcher.cs:line 559
   at SynthEBD.Patcher.RunPatcher() in D:\a\SynthEBD\SynthEBD\SynthEBD\Patcher\Patcher.cs:line 296
   at SynthEBD.VM_RunButton.<>c__DisplayClass7_0.<<-ctor>b__0>d.MoveNext() in D:\a\SynthEBD\SynthEBD\SynthEBD\RunButton\VM_RunButton.cs:line 76

SynthEBD Version: 0.9.6.3

Run Mode: Standalone

Patcher Settings Creation Log:
Found settings source path at C:\Skyrim Modding Shit\SynthEBD\SynthEBD_v0.9.6.3\Settings\SettingsSource.json
Source Settings: 
Load Settings from Portable Folder: False
Portable Folder Location: 

Patcher Environment Creation Log:
Found environment source path at C:\Skyrim Modding Shit\SynthEBD\SynthEBD_v0.9.6.3\Settings\EnvironmentSource.json
Source Settings: 
Skyrim Version: SkyrimSE
Game Environment Directory: C:\Program Files (x86)\Steam\steamapps\common\Skyrim Special Edition\Data

Patcher State:
Main Settings:
Apply Assets: True
Apply BodyShapes via: BodySlide
Apply BodySlides via: OBody
Apply Height: True
Apply Head Parts: True
Use Consistency: True
Mod Manager Type: Vortex
Staging Folder exists
Primary Config Files
	ALT2 CBBE 4K Compressed
	Bijin Skins 4K CBBE
	Binibini Skin 1.5 CBBE 3BA
	Bits and Pieces Female Skin 1.7 4K CBBE 3BA (RBT and RSV)
	Bits and Pieces Male Skin 1.9 4K (RBT)
	Demoniac 4K CBBE
	Diamond Skin 2.2 CBBE
	FA Dibellan 4K
	Fair Skin Complexion v11.1 CBBE 3BA
	Leyenda Skin 4.0
	Mature Skin CBBE HD
	Realore Skin Ultima V2.1.1 CBBE
	Reverie Skin 1.9.1 CBBE
	Tempered Skins for Females CBBE
	Tempered Skins for Males - SOS
	Vitruvia SOS 4K
MixIn Config Files
	CBBE 3BA Custom Normal Maps
	CBBE 3BAv2 Vagina Textures Set 4K
Male BodyGen Configs
Female BodyGen Configs
	MCSmarties Diverse Races Adaptation
Male BodySlides: 17 (10) annotated
Female BodySlides: 52 (45) annotated
Height Configs: 1
Eyebrows: 0 HeadParts
Eyes: 0 HeadParts
Face: 0 HeadParts
FacialHair: 0 HeadParts
Hair: 0 HeadParts
Misc: 0 HeadParts
Scars: 0 HeadParts

Current NPC: Sister Eda | _SLSD_NPC_SisterEda | 026C79:SexLab_DibellaCult.esp

**Comment by Piranha91** [comment]
Thanks for the report. Can you try 0.9.6.5?

**Comment by greengrill** [comment]
It seems to work for now but the other version worked at first and then started crashing. I'll let you know if this happens again but thank you!
