### ISSUE TITLE
Crashes on every run

### ISSUE THREAD

**Issue by Topsy9** [Synthesis-Collective/SynthEBD#117]
Everytime I run the patcher i get this. I tried reinstalling and only having one texture config installed, but i get the same thing. It worked for me in the past, so i will try a version earlier and update.

SynthEBD has crashed with the following error:
An object implementing IHandleObservableErrors (often a ReactiveCommand or ObservableAsPropertyHelper) has errored, thereby breaking its observable pipeline. To prevent this, ensure the pipeline does not error, or Subscribe to the ThrownExceptions property of the object in question to handle the erroneous case.
   at ReactiveUI.RxApp.<>c__DisplayClass9_0.<.cctor>b__2() in /_/src/ReactiveUI/RxApp.cs:line 109
   at System.Reactive.Concurrency.Scheduler.Invoke(Action action) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 253
   at System.Reactive.Concurrency.Scheduler.<>c.<Schedule>b__74_0(IScheduler _, Action a) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 37
   at System.Reactive.Concurrency.DispatcherScheduler.<>c__DisplayClass12_0`1.<Schedule>b__0() in /_/src/ReactiveUI.Uwp/Rx/Concurrency/DispatcherScheduler.cs:line 98
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

List with a non zero KSIZ counter did not follow up with expected type: KWDA
   at Mutagen.Bethesda.Skyrim.SkyrimModMixIn.<>c__DisplayClass19_0`1.<EnumerateMajorRecords>b__1(Exception e)
   at Noggog.EnumerableExt.Catch[T](IEnumerable`1 e, Action`1 onException)+MoveNext() in D:\a\CSharpExt\CSharpExt\Noggog.CSharpExt\Extensions\EnumerableExt.cs:line 287
   at Mutagen.Bethesda.OverrideMixIns.WinningOverrides[TMajor](IEnumerable`1 mods, Boolean includeDeletedRecords)+MoveNext()
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at SynthEBD.Patcher.RunPatcher() in D:\a\SynthEBD\SynthEBD\SynthEBD\Patcher\Patcher.cs:line 305
   at SynthEBD.VM_RunButton.<>c__DisplayClass7_0.<<-ctor>b__0>d.MoveNext() in D:\a\SynthEBD\SynthEBD\SynthEBD\RunButton\VM_RunButton.cs:line 76

List with a non zero KSIZ counter did not follow up with expected type: KWDA
   at Mutagen.Bethesda.Plugins.Binary.Overlay.BinaryOverlayList.FactoryByCount[T](OverlayStream stream, BinaryOverlayFactoryPackage package, Int32 itemLength, Int32 countLength, RecordType trigger, RecordType countType, SpanFactory`1 getter)
   at Mutagen.Bethesda.Skyrim.NpcBinaryOverlay.FillRecordType(OverlayStream stream, Int32 finalPos, Int32 offset, RecordType type, PreviousParse lastParsed, Dictionary`2 recordParseCount, TypedParseParams translationParams)
   at Mutagen.Bethesda.Plugins.Binary.Overlay.PluginBinaryOverlay.FillSubrecordTypes(OverlayStream stream, Int32 finalPos, Int32 offset, TypedParseParams translationParams, RecordTypeFillWrapper fill)

SynthEBD Version: 1.0.0.5

I tried the previous version, same thing. I also tried using it through synthesis, but i get this error before i can even run it

System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.IO.Path.Combine(String path1, String path2)
   at SynthEBD.App.CanRunPatch(IRunnabilityState state) in C:\Users\\AppData\Local\Temp\Synthesis\l5wflbxl.agh\Git\mnshy2kc.bj1\Runner\SynthEBD\App.xaml.cs:line 119
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.<>c__DisplayClass19_0.<<AddRunnabilityCheck>b__0>d.MoveNext() in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 163
--- End of stack trace from previous location ---
   at Mutagen.Bethesda.Synthesis.SynthesisPipeline.CheckRunnability(CheckRunnability args, IFileSystem fileSystem) in D:\a\Synthesis\Synthesis\Mutagen.Bethesda.Synthesis\Pipeline\SynthesisPipeline.cs:line 184

**Comment by Topsy9** [comment]
Thank you. Ill try some things, maybe reinstall all my mods and report back if there are changes.

**Comment by Topsy9** [comment]
I reinstalled all my mods, but it took so long that I don't even want to risk breaking anything so I just went with a different texture mod. Closing the issue
