### ISSUE TITLE
Version 0.7 and up crash on startup

### ISSUE THREAD

**Issue by izomiac** [Synthesis-Collective/SynthEBD#15]
The "SynthEBD 0.7 Experimental v7 - Laptop" version works, as does 0.6, but the officially released 0.7 and later versions crash with the following errors...  I'm launching it from Mod Organizer 2 and my Skyrim Data folder that apparently isn't being found is at: "C:\Program Files (x86)\Steam\steamapps\common\SkyrimVR\Data".

```
SynthEBD has crashed with the following error:
The invocation of the constructor on type 'SynthEBD.MainWindow' that matches the specified binding constraints threw an exception.
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

The type initializer for 'SynthEBD.PatcherEnvironmentProvider' threw an exception.
   at SynthEBD.VM_SettingsHeight..ctor() in D:\a\SynthEBD\SynthEBD\SynthEBD\Settings\Settings_Height\VM_SettingsHeight.cs:line 12
   at SynthEBD.MainWindow_ViewModel..ctor() in D:\a\SynthEBD\SynthEBD\SynthEBD\MainWindow_ViewModel.cs:line 16
   at SynthEBD.MainWindow..ctor() in D:\a\SynthEBD\SynthEBD\SynthEBD\MainWindow.xaml.cs:line 21
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)

Data folder for SkyrimSE cannot be found automatically
   at Mutagen.Bethesda.Installs.DI.GameLocator.GetDataDirectory(GameRelease release)
   at Mutagen.Bethesda.Installs.DI.GameLocator.Mutagen.Bethesda.Environments.DI.IDataDirectoryLookup.Get(GameRelease release)
   at Mutagen.Bethesda.Environments.DI.DataDirectoryProvider.get_Path()
   at Mutagen.Bethesda.Plugins.Order.DI.ImplicitListingsProvider.<Get>b__8_0(ModKey x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Mutagen.Bethesda.Plugins.Order.DI.LoadOrderListingsProvider.Get()
   at Mutagen.Bethesda.Environments.GameEnvironmentBuilder`2.Build()
   at SynthEBD.PatcherEnvironmentProvider.<.ctor>b__27_8(ValueTuple`3 inputs) in D:\a\SynthEBD\SynthEBD\SynthEBD\General_Aux\PatcherEnvironmentProvider.cs:line 64
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Select.cs:line 39
--- End of stack trace from previous location ---
   at System.Reactive.PlatformServices.ExceptionServicesImpl.Rethrow(Exception exception) in /_/Rx.NET/Source/src/System.Reactive/Internal/ExceptionServicesImpl.cs:line 19
   at System.Reactive.ExceptionHelpers.Throw(Exception exception) in /_/Rx.NET/Source/src/System.Reactive/Internal/ExceptionServices.cs:line 16
   at System.Reactive.Stubs.<>c.<.cctor>b__2_1(Exception ex) in /_/Rx.NET/Source/src/System.Reactive/Internal/Stubs.cs:line 16
   at System.Reactive.AnonymousSafeObserver`1.OnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 62
   at System.Reactive.Sink`1.ForwardOnError(Exception error) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 60
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Select.cs:line 43
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 49
   at System.Reactive.Linq.ObservableImpl.DistinctUntilChanged`2._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/DistinctUntilChanged.cs:line 72
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 49
   at System.Reactive.Linq.ObservableImpl.CombineLatestSink`1.Next(Int32 index) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/CombineLatest.cs:line 277
   at System.Reactive.Linq.ObservableImpl.CombineLatestObserver`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/CombineLatest.cs:line 347
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 49
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Select.cs:line 47
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 49
   at System.Reactive.Linq.ObservableImpl.DistinctUntilChanged`2._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/DistinctUntilChanged.cs:line 72
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 49
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Select.cs:line 47
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 49
   at System.Reactive.Linq.ObservableImpl.Where`1.Predicate._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Where.cs:line 54
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 49
   at System.Reactive.Linq.ObservableImpl.Switch`1._.InnerObserver.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Switch.cs:line 101
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 49
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Select.cs:line 47
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 49
   at System.Reactive.IdentitySink`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/Internal/IdentitySink.cs:line 15
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 49
   at System.Reactive.Linq.ObservableImpl.ToObservableRecursive`1._.LoopRec(IScheduler scheduler) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/ToObservable.cs:line 115
   at System.Reactive.Linq.ObservableImpl.ToObservableRecursive`1._.<>c.<Run>b__3_0(IScheduler innerScheduler, _ this) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/ToObservable.cs:line 55
   at System.Reactive.Concurrency.ImmediateScheduler.Schedule[TState](TState state, Func`3 action) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/ImmediateScheduler.cs:line 41
   at System.Reactive.Linq.ObservableImpl.ToObservableRecursive`1._.Run(IEnumerable`1 source, IScheduler scheduler) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/ToObservable.cs:line 41
   at System.Reactive.Linq.ObservableImpl.ToObservableRecursive`1.Run(_ sink) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/ToObservable.cs:line 24
   at System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in /_/Rx.NET/Source/src/System.Reactive/Internal/Producer.cs:line 125
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer) in /_/Rx.NET/Source/src/System.Reactive/Observable.Extensions.cs:line 367
   at System.Reactive.TailRecursiveSink`1.Drain() in /_/Rx.NET/Source/src/System.Reactive/Internal/TailRecursiveSink.cs:line 128
   at System.Reactive.TailRecursiveSink`1.Run(IEnumerable`1 sources) in /_/Rx.NET/Source/src/System.Reactive/Internal/TailRecursiveSink.cs:line 34
   at System.Reactive.Linq.ObservableImpl.Concat`1.Run(_ sink) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Concat.cs:line 20
   at System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in /_/Rx.NET/Source/src/System.Reactive/Internal/Producer.cs:line 125
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer) in /_/Rx.NET/Source/src/System.Reactive/Observable.Extensions.cs:line 367
   at System.Reactive.Sink`2.Run(IObservable`1 source) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 89
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector.Run(_ sink) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Select.cs:line 22
   at System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in /_/Rx.NET/Source/src/System.Reactive/Internal/Producer.cs:line 125
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer) in /_/Rx.NET/Source/src/System.Reactive/Observable.Extensions.cs:line 367
   at System.Reactive.Linq.ObservableImpl.Switch`1._.OnNext(IObservable`1 value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Switch.cs:line 59
   at System.Reactive.Sink`1.ForwardOnNext(TTarget value) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 49
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Select.cs:line 47
   at System.Reactive.Linq.ObservableImpl.ReturnImmediate`1.Run(IObserver`1 observer) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Return.cs:line 62
   at System.Reactive.BasicProducer`1.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in /_/Rx.NET/Source/src/System.Reactive/Internal/Producer.cs:line 66
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer) in /_/Rx.NET/Source/src/System.Reactive/Observable.Extensions.cs:line 367
   at System.Reactive.Sink`2.Run(IObservable`1 source) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 89
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector.Run(_ sink) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Select.cs:line 22
   at System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in /_/Rx.NET/Source/src/System.Reactive/Internal/Producer.cs:line 125
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer) in /_/Rx.NET/Source/src/System.Reactive/Observable.Extensions.cs:line 367
   at System.Reactive.Sink`2.Run(IObservable`1 source) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 89
   at System.Reactive.Linq.ObservableImpl.Switch`1.Run(_ sink) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Switch.cs:line 20
   at System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in /_/Rx.NET/Source/src/System.Reactive/Internal/Producer.cs:line 125
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer) in /_/Rx.NET/Source/src/System.Reactive/Observable.Extensions.cs:line 367
   at System.Reactive.Sink`2.Run(IObservable`1 source) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 89
   at System.Reactive.Linq.ObservableImpl.Where`1.Predicate.Run(_ sink) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Where.cs:line 27
   at System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in /_/Rx.NET/Source/src/System.Reactive/Internal/Producer.cs:line 125
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer) in /_/Rx.NET/Source/src/System.Reactive/Observable.Extensions.cs:line 367
   at System.Reactive.Sink`2.Run(IObservable`1 source) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 89
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector.Run(_ sink) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Select.cs:line 22
   at System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in /_/Rx.NET/Source/src/System.Reactive/Internal/Producer.cs:line 125
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer) in /_/Rx.NET/Source/src/System.Reactive/Observable.Extensions.cs:line 367
   at System.Reactive.Sink`2.Run(IObservable`1 source) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 89
   at System.Reactive.Linq.ObservableImpl.DistinctUntilChanged`2.Run(_ sink) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/DistinctUntilChanged.cs:line 24
   at System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in /_/Rx.NET/Source/src/System.Reactive/Internal/Producer.cs:line 125
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer) in /_/Rx.NET/Source/src/System.Reactive/Observable.Extensions.cs:line 367
   at System.Reactive.Sink`2.Run(IObservable`1 source) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 89
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector.Run(_ sink) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Select.cs:line 22
   at System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in /_/Rx.NET/Source/src/System.Reactive/Internal/Producer.cs:line 125
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer) in /_/Rx.NET/Source/src/System.Reactive/Observable.Extensions.cs:line 367
   at System.Reactive.Linq.ObservableImpl.CombineLatest`4._.Run(IObservable`1 source1, IObservable`1 source2, IObservable`1 source3) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/CombineLatest.NAry.cs:line 54
   at System.Reactive.Linq.ObservableImpl.CombineLatest`4.Run(_ sink) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/CombineLatest.NAry.cs:line 32
   at System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in /_/Rx.NET/Source/src/System.Reactive/Internal/Producer.cs:line 125
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer) in /_/Rx.NET/Source/src/System.Reactive/Observable.Extensions.cs:line 367
   at System.Reactive.Sink`2.Run(IObservable`1 source) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 89
   at System.Reactive.Linq.ObservableImpl.DistinctUntilChanged`2.Run(_ sink) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/DistinctUntilChanged.cs:line 24
   at System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in /_/Rx.NET/Source/src/System.Reactive/Internal/Producer.cs:line 125
   at System.ObservableExtensions.SubscribeSafe[T](IObservable`1 source, IObserver`1 observer) in /_/Rx.NET/Source/src/System.Reactive/Observable.Extensions.cs:line 367
   at System.Reactive.Sink`2.Run(IObservable`1 source) in /_/Rx.NET/Source/src/System.Reactive/Internal/Sink.cs:line 89
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector.Run(_ sink) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Select.cs:line 22
   at System.Reactive.Producer`2.<>c.<SubscribeRaw>b__1_0(ValueTuple`2 tuple) in /_/Rx.NET/Source/src/System.Reactive/Internal/Producer.cs:line 121
   at System.Reactive.Concurrency.Scheduler.<>c__75`1.<ScheduleAction>b__75_0(IScheduler _, ValueTuple`2 tuple) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 65
   at System.Reactive.Concurrency.CurrentThreadScheduler.Schedule[TState](TState state, TimeSpan dueTime, Func`3 action) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/CurrentThreadScheduler.cs:line 101
   at System.Reactive.Concurrency.LocalScheduler.Schedule[TState](TState state, Func`3 action) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/LocalScheduler.cs:line 32
   at System.Reactive.Concurrency.Scheduler.ScheduleAction[TState](IScheduler scheduler, TState state, Action`1 action) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 61
   at System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in /_/Rx.NET/Source/src/System.Reactive/Internal/Producer.cs:line 102
   at System.Reactive.Producer`2.Subscribe(IObserver`1 observer) in /_/Rx.NET/Source/src/System.Reactive/Internal/Producer.cs:line 97
   at System.ObservableExtensions.Subscribe[T](IObservable`1 source, Action`1 onNext) in /_/Rx.NET/Source/src/System.Reactive/Observable.Extensions.cs:line 63
   at SynthEBD.PatcherEnvironmentProvider..ctor() in D:\a\SynthEBD\SynthEBD\SynthEBD\General_Aux\PatcherEnvironmentProvider.cs:line 46
   at SynthEBD.PatcherEnvironmentProvider..cctor() in D:\a\SynthEBD\SynthEBD\SynthEBD\General_Aux\PatcherEnvironmentProvider.cs:line 15
```

```
SynthEBD has crashed with the following error:
Object reference not set to an instance of an object.
   at SynthEBD.App.Application_DispatcherUnhandledException(Object sender, DispatcherUnhandledExceptionEventArgs e) in D:\a\SynthEBD\SynthEBD\SynthEBD\App.xaml.cs:line 36
   at System.Windows.Threading.Dispatcher.CatchException(Exception e)
   at System.Windows.Threading.Dispatcher.CatchExceptionStatic(Object source, Exception e)
   at System.Windows.Threading.ExceptionWrapper.CatchException(Object source, Exception e, Delegate catchHandler)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by Piranha91** [comment]
Thanks for the report! Does the latest 0.7.2 work, or does it also crash? If it doesn't work, can you please try this version [here ](https://drive.google.com/file/d/1CheOxUnHr1q8Ju3CZ2pLYJ2t2RL_27-L/view?usp=sharing)and let me know how it does?

**Comment by Piranha91** [comment]
I must have reverted a change to the environment creator at some point - it used to trigger the custom environment popup if I pointed the environment directory at an invalid folder; now it just accepts that directory without complaint and then builds from the default one. Guess I know what I'm doing tonight :)

**Comment by Piranha91** [comment]
Could you please check if this version is able to create the environment for you? https://drive.google.com/file/d/1HUjSP7tt-0f8MauHtbnboI4mCIrSSUKQ/view?usp=sharing

**Comment by izomiac** [comment]
That version works for me.  There's a minor issue where it crashes on the next load after selecting the option "Load Settings from Portable Data Folder" but not selecting a custom location so it tries to load them from the default Data directory.  But all-in-all it works great.

**Comment by Piranha91** [comment]
If you have a chance, could you see if the crash when toggling the portable data folder is resolved in 0.7.3? Thanks!

**Comment by izomiac** [comment]
I'd be happy to when I get back home.  I'm stuck in the hospital until I
can clear an infection.  I should be fine and back to my PC in a couple of
days.

**Comment by Piranha91** [comment]
Ouch, sorry to hear that. Best of luck with the recovery!

**Comment by izomiac** [comment]
The official release opens fine for me, but still seems to have the portable data folder issue.  Or at least I think.  I'm feeling better and am out of the hospital, but my concentration and focus is shot for now so treat this report as if an unreliable half-wit wrote it.

```
SynthEBD has crashed with the following error:
The invocation of the constructor on type 'SynthEBD.MainWindow' that matches the specified binding constraints threw an exception.
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

The type initializer for 'SynthEBD.PatcherEnvironmentProvider' threw an exception.
   at SynthEBD.VM_SettingsHeight..ctor() in D:\a\SynthEBD\SynthEBD\SynthEBD\Settings\Settings_Height\VM_SettingsHeight.cs:line 12
   at SynthEBD.MainWindow_ViewModel..ctor() in D:\a\SynthEBD\SynthEBD\SynthEBD\MainWindow_ViewModel.cs:line 16
   at SynthEBD.MainWindow..ctor() in D:\a\SynthEBD\SynthEBD\SynthEBD\MainWindow.xaml.cs:line 21
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)

Object reference not set to an instance of an object.
   at SynthEBD.Paths.RefreshRelativePath() in D:\a\SynthEBD\SynthEBD\SynthEBD\GUI_Aux\ExpectedPaths.cs:line 107
   at SynthEBD.Paths.UpdatePaths() in D:\a\SynthEBD\SynthEBD\SynthEBD\GUI_Aux\ExpectedPaths.cs:line 90
   at SynthEBD.Paths..ctor() in D:\a\SynthEBD\SynthEBD\SynthEBD\GUI_Aux\ExpectedPaths.cs:line 56
   at SynthEBD.SettingsIO_Misc.GetSettingsSource() in D:\a\SynthEBD\SynthEBD\SynthEBD\Settings\SettingsIO\SettingsIO_Misc.cs:line 26
   at SynthEBD.PatcherEnvironmentProvider..ctor() in D:\a\SynthEBD\SynthEBD\SynthEBD\General_Aux\PatcherEnvironmentProvider.cs:line 27
   at SynthEBD.PatcherEnvironmentProvider..cctor() in D:\a\SynthEBD\SynthEBD\SynthEBD\General_Aux\PatcherEnvironmentProvider.cs:line 15

```

```
SynthEBD has crashed with the following error:
Object reference not set to an instance of an object.
   at SynthEBD.App.Application_DispatcherUnhandledException(Object sender, DispatcherUnhandledExceptionEventArgs e) in D:\a\SynthEBD\SynthEBD\SynthEBD\App.xaml.cs:line 36
   at System.Windows.Threading.Dispatcher.CatchException(Exception e)
   at System.Windows.Threading.Dispatcher.CatchExceptionStatic(Object source, Exception e)
   at System.Windows.Threading.ExceptionWrapper.CatchException(Object source, Exception e, Delegate catchHandler)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```

**Comment by Piranha91** [comment]
Glad you're out! Good luck with the recovery. Thanks for providing the stack trace; I think I see the issue. If you get a chance, can you please try [this version]([url](https://drive.google.com/file/d/1nKTRj3B771qDepRl9PqMudDKMmYIini6/view?usp=sharing))?

**Comment by Piranha91** [comment]
0.7.5 overhauls the startup - if you have a chance, can you let me know if it fixes the issue?

**Comment by izomiac** [comment]
Yes, everything seems to be working correctly in 0.7.5
