### ISSUE TITLE
Mod Organizer Hang on startup

### ISSUE THREAD

**Issue by holto243** [Synthesis-Collective/SynthEBD#18]
Hello,
I can do a fresh install of SynthEBD and it runs fine but as soon as I run the patch once, every time I start it through mod organizer it hangs and doesn't open.
If I unlock and close MO it tells me Mod organizer is waiting on SynthEBD.exe to close
No log created.
The only way I can start it is by deleting and reinstalling SynthEBD
Same problem from 0.6 though to 0.7.3

**Comment by holto243** [comment]
I did another full fresh install and SynthEBD opens again but I am now getting the following crash report when patching

SynthEBD has crashed with the following error:
An object implementing IHandleObservableErrors (often a ReactiveCommand or ObservableAsPropertyHelper) has errored, thereby breaking its observable pipeline. To prevent this, ensure the pipeline does not error, or Subscribe to the ThrownExceptions property of the object in question to handle the erroneous case.
   at ReactiveUI.RxApp.<>c__DisplayClass9_0.<.cctor>b__2() in /_/src/ReactiveUI/RxApp.cs:line 109
   at System.Reactive.Concurrency.Scheduler.Invoke(Action action) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 253
   at System.Reactive.Concurrency.Scheduler.<>c.<Schedule>b__74_0(IScheduler _, Action a) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 37
   at System.Reactive.Concurrency.DispatcherScheduler.<>c__DisplayClass12_0`1.<Schedule>b__0() in /_/src/ReactiveUI.Uwp/Rx/Concurrency/DispatcherScheduler.cs:line 98
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

The best overloaded method match for 'SynthEBD.RecordGenerator.SetViaFormKeyReplacement(Mutagen.Bethesda.Plugins.Records.IMajorRecord, object, string)' has some invalid arguments
   at CallSite.Target(Closure , CallSite , Type , Object , Object , String )
   at SynthEBD.RecordGenerator.AssignGenericAssetPaths(NPCInfo npcInfo, List`1 nonHardcodedPaths, Npc rootNPC, ILinkCache`2 recordTemplateLinkCache, SkyrimMod outputMod, Int32 longestPath, Boolean assignFromTemplate, Boolean suppressMissingPathErrors, Dictionary`2 npcObjectMap, Dictionary`2 objectCaches, List`1 assignedPaths) in D:\a\SynthEBD\SynthEBD\SynthEBD\Patcher\Asset Patching\RecordGenerator.cs:line 147
   at SynthEBD.RecordGenerator.CombinationToRecords(List`1 combinations, NPCInfo npcInfo, ILinkCache`2 recordTemplateLinkCache, Dictionary`2 npcObjectMap, Dictionary`2 objectCaches, SkyrimMod outputMod, List`1 assignedPaths) in D:\a\SynthEBD\SynthEBD\SynthEBD\Patcher\Asset Patching\RecordGenerator.cs:line 29
   at SynthEBD.Patcher.MainLoop(IEnumerable`1 npcCollection, Boolean skipLinkedSecondaryNPCs, SkyrimMod outputMod, CategorizedFlattenedAssetPacks sortedAssetPacks, BodyGenConfigs bodyGenConfigs, Settings_OBody oBodySettings, HeightConfig currentHeightConfig, Dictionary`2 consistency, HashSet`1 specificNPCAssignments, BlockList blockList, HashSet`1 linkedNPCGroups, ILinkCache`2 recordTemplateLinkCache, Int32 npcCounter, HashSet`1 generatedLinkGroups, HashSet`1 skippedLinkedNPCs, Keyword EBDFaceKW, Keyword EBDScriptKW, Spell bodySlideAssignmentSpell, VM_StatusBar statusBar, HashSet`1 headPartNPCs) in D:\a\SynthEBD\SynthEBD\SynthEBD\Patcher\Patcher.cs:line 408
   at SynthEBD.Patcher.RunPatcher(List`1 assetPacks, BodyGenConfigs bodyGenConfigs, List`1 heightConfigs, Dictionary`2 consistency, HashSet`1 specificNPCAssignments, BlockList blockList, HashSet`1 linkedNPCNameExclusions, HashSet`1 linkedNPCGroups, ILinkCache`2 recordTemplateLinkCache, List`1 recordTemplatePlugins, VM_StatusBar statusBar) in D:\a\SynthEBD\SynthEBD\SynthEBD\Patcher\Patcher.cs:line 124
   at SynthEBD.VM_RunButton.<.ctor>b__0_0(CancellationToken _) in D:\a\SynthEBD\SynthEBD\SynthEBD\RunButton\VM_RunButton.cs:line 38

**Comment by Piranha91** [comment]
I haven't tried to address this issue directly because I haven't been able to reproduce it, but 0.7.4 is a somewhat extensive refactor of the startup systems. Please give it a shot and let me know if the issue is resolved.

**Comment by Piranha91** [comment]
Close due to inactivity.
