### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by aedreu** [Synthesis-Collective/SynthEBD#19]
I matched the mutagen version to get out of the blocking error then got this:

SynthEBD has crashed with the following error:
Exception has been thrown by the target of an invocation.
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at System.Xaml.Schema.SafeReflectionInvoker.CreateInstanceCritical(Type type, Object[] arguments)
   at System.Xaml.Schema.XamlTypeInvoker.CreateInstance(Object[] arguments)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateInstanceWithCtor(XamlType xamlType, Object[] args)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateInstance(XamlType xamlType, Object[] args)
   at System.Xaml.XamlObjectWriter.Logic_CreateAndAssignToParentStart(ObjectWriterContext ctx)
   at System.Xaml.XamlObjectWriter.WriteStartMember(XamlMember property)
   at System.Xaml.XamlWriter.WriteNode(XamlReader reader)
   at System.Windows.Markup.WpfXamlLoader.TransformNodes(XamlReader xamlReader, XamlObjectWriter xamlWriter, Boolean onlyLoadOneNode, Boolean skipJournaledProperties, Boolean shouldPassLineNumberInfo, IXamlLineInfo xamlLineInfo, IXamlLineInfoConsumer xamlLineInfoConsumer, XamlContextStack`1 stack, IStyleConnector styleConnector)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Object reference not set to an instance of an object.
   at SynthEBD.Settings_OBody.ImportBodySlides(HashSet`1 templateDescriptors) in C:\Users\komdr\AppData\Local\Temp\Synthesis\iloh2lqs.v5u\Git\f0sy3tnq.2so\Runner\SynthEBD\Settings\Settings_OBody\Settings_OBody.cs:line 53
   at SynthEBD.MainWindow_ViewModel.LoadInitialSettingsViewModels() in C:\Users\komdr\AppData\Local\Temp\Synthesis\iloh2lqs.v5u\Git\f0sy3tnq.2so\Runner\SynthEBD\MainWindow_ViewModel.cs:line 101
   at SynthEBD.MainWindow_ViewModel..ctor() in C:\Users\komdr\AppData\Local\Temp\Synthesis\iloh2lqs.v5u\Git\f0sy3tnq.2so\Runner\SynthEBD\MainWindow_ViewModel.cs:line 56
   at SynthEBD.MainWindow..ctor() in C:\Users\komdr\AppData\Local\Temp\Synthesis\iloh2lqs.v5u\Git\f0sy3tnq.2so\Runner\SynthEBD\MainWindow.xaml.cs:line 21
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)

**Comment by Piranha91** [comment]
Sorry, what do you mean by "matched the mutagen version"? Are you trying to run SynthEBD through Synthesis? SynthEBD is not a Synthesis patcher; it's a standalone executable.

**Comment by aedreu** [comment]
shit sorry I'm a noob at this didn't realise where the releases were in git hub, so i just inputed into synthesis yea. Getting this crash now from SynthEBD.exe through MO2:

SynthEBD has crashed with the following error:
Exception has been thrown by the target of an invocation.
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at System.Xaml.Schema.SafeReflectionInvoker.CreateInstanceCritical(Type type, Object[] arguments)
   at System.Xaml.Schema.XamlTypeInvoker.CreateInstance(Object[] arguments)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateInstanceWithCtor(XamlType xamlType, Object[] args)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateInstance(XamlType xamlType, Object[] args)
   at System.Xaml.XamlObjectWriter.Logic_CreateAndAssignToParentStart(ObjectWriterContext ctx)
   at System.Xaml.XamlObjectWriter.WriteStartMember(XamlMember property)
   at System.Xaml.XamlWriter.WriteNode(XamlReader reader)
   at System.Windows.Markup.WpfXamlLoader.TransformNodes(XamlReader xamlReader, XamlObjectWriter xamlWriter, Boolean onlyLoadOneNode, Boolean skipJournaledProperties, Boolean shouldPassLineNumberInfo, IXamlLineInfo xamlLineInfo, IXamlLineInfoConsumer xamlLineInfoConsumer, XamlContextStack`1 stack, IStyleConnector styleConnector)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Object reference not set to an instance of an object.
   at SynthEBD.Settings_OBody.ImportBodySlides(HashSet`1 templateDescriptors) in D:\a\SynthEBD\SynthEBD\SynthEBD\Settings\Settings_OBody\Settings_OBody.cs:line 53
   at SynthEBD.MainWindow_ViewModel.LoadInitialSettingsViewModels() in D:\a\SynthEBD\SynthEBD\SynthEBD\MainWindow_ViewModel.cs:line 101
   at SynthEBD.MainWindow_ViewModel..ctor() in D:\a\SynthEBD\SynthEBD\SynthEBD\MainWindow_ViewModel.cs:line 56
   at SynthEBD.MainWindow..ctor() in D:\a\SynthEBD\SynthEBD\SynthEBD\MainWindow.xaml.cs:line 21
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)

**Comment by Piranha91** [comment]
Please let me know if the latest 0.7.4 build solves the issues. Sorry for the slow response.

**Comment by Piranha91** [comment]
Should be fixed in 0.7.5!

**Comment by aedreu** [comment]
Yea I got it to work, I had a few bad bodyslide files like ShmokeyBoah29 had who wrote about it on on the nexus forums for zEBD.
