### ISSUE TITLE
"Crash" adding specific NPC assignment

### ISSUE THREAD

**Issue by rydoq** [Synthesis-Collective/SynthEBD#2]
![image](https://user-images.githubusercontent.com/100347783/155499056-47dd9f86-f203-40bb-adac-a4e83f9da887.png)

Upon clicking "ADD NEW" under Specific NPC Assignment, SynthEBD comes up with that window, but does not actually crash. Though the program does not actually crash, there is no new NPC dropdown or anything, so the feature does not seem to work. Using version 0.2.0.

Below is the log:
<details>Object reference not set to an instance of an object.
   at SynthEBD.VM_SpecificNPCAssignment..ctor(ObservableCollection`1 assetPacks, VM_SettingsBodyGen bodyGenSettings, VM_SettingsOBody oBodySettings, VM_Settings_General generalSettingsVM) in Z:\Synthesis Development\SynthEBD\SynthEBD\Classes_Core\ViewModels\VM_SpecificNPCAssignment.cs:line 63
   at SynthEBD.VM_SpecificNPCAssignmentsUI.<>c__DisplayClass0_0.<.ctor>b__1(Object _) in Z:\Synthesis Development\SynthEBD\SynthEBD\Settings\Settings_SpecificNPCAssignments\VM_SpecificNPCAssignmentsUI.cs:line 21
   at SynthEBD.RelayCommand.Execute(Object parameter) in Z:\Synthesis Development\SynthEBD\SynthEBD\GUI_Aux\RelayCommand.cs:line 34
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)</details>

**Comment by Daikichi-Takahey** [comment]
I have the same problem.
![スクリーンショット (19)](https://user-images.githubusercontent.com/100354903/155521729-1d30b5b2-b7e4-4689-9627-7826a397d6a7.png)

**Comment by Piranha91** [comment]
Fixed in v0.3.0
