### ISSUE TITLE
Crash when pressing "Run"

### ISSUE THREAD

**Issue by Foroneus** [Synthesis-Collective/SynthEBD#29]
Lately, SynthEBD has been crashing when I click run, even when there isn't any config files selected. It gives this message:

SynthEBD has crashed with the following error:
An object implementing IHandleObservableErrors (often a ReactiveCommand or ObservableAsPropertyHelper) has errored, thereby breaking its observable pipeline. To prevent this, ensure the pipeline does not error, or Subscribe to the ThrownExceptions property of the object in question to handle the erroneous case.
   at ReactiveUI.RxApp.<>c__DisplayClass9_0.<.cctor>b__2() in /_/src/ReactiveUI/RxApp.cs:line 109
   at System.Reactive.Concurrency.Scheduler.Invoke(Action action) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 253
   at System.Reactive.Concurrency.Scheduler.<>c.<Schedule>b__74_0(IScheduler _, Action a) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 37
   at System.Reactive.Concurrency.DispatcherScheduler.<>c__DisplayClass12_0`1.<Schedule>b__0() in /_/src/ReactiveUI.Uwp/Rx/Concurrency/DispatcherScheduler.cs:line 96
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Object reference not set to an instance of an object.
   at SynthEBD.VM_SpecificNPCAssignment.DumpViewModelToModel(VM_SpecificNPCAssignment viewModel) in D:\a\SynthEBD\SynthEBD\SynthEBD\Classes_Core\ViewModels\VM_SpecificNPCAssignment.cs:line 325
   at SynthEBD.VM_SpecificNPCAssignmentsUI.DumpViewModelToModels(VM_SpecificNPCAssignmentsUI viewModel, HashSet`1 models) in D:\a\SynthEBD\SynthEBD\SynthEBD\Settings\Settings_SpecificNPCAssignments\VM_SpecificNPCAssignmentsUI.cs:line 150
   at SynthEBD.SaveLoader.DumpViewModelsToModels() in D:\a\SynthEBD\SynthEBD\SynthEBD\SaveLoader.cs:line 147
   at SynthEBD.VM_RunButton.<>c__DisplayClass2_0.<<-ctor>b__0>d.MoveNext() in D:\a\SynthEBD\SynthEBD\SynthEBD\RunButton\VM_RunButton.cs:line 44

**Comment by Foroneus** [comment]
Oh, I figured out the problem by actually looking it, I was messing around with what some of the menus looked like and I left an empty specific NPC assignment field, which is seemingly what caused it to crash. Not sure if I should close it though since I imagine this is still a bug.

**Comment by Piranha91** [comment]
Sorry, which version of SynthEBD is this? I wasn't able to replicate the crash on the latest version. Is this what caused it to crash for you?

![image](https://user-images.githubusercontent.com/63175798/179385914-e2a8519e-aaab-4277-835e-4a8f64c8e520.png)

**Comment by Piranha91** [comment]
Should be fixed in 0.7.7.1 - please let me know if you continue seeing this issue.
