### ISSUE TITLE
Overwritten asset paths while importing an asset pack with very long directory structure

### ISSUE THREAD

**Issue by leonardovcr** [Synthesis-Collective/SynthEBD#40]
Hi,

I'm trying to create an asset pack that contains (among others) one "femaleold" body normal and two "female" body normal versions, with paths and filenames ending like this:

(1) ...actors\character\femaleold\FemaleBody_1_msn.dds (version for ElderRace)
(2) ...actors\character\female\femalebody_1_msn.dds (main version)
(3) ...actors\character\female\femalebody_1_msn.dds (alternate version)

Unfortunately, the original texture pack .7z file has very long paths, which gets even bigger with asset prefix, etc. During import ("install config from archive") synthEBD trims and changes all the paths to a very short one, also changing the textures filenames, to something like this:

(1) <prefix>\FemaleBody_1_msn\1.dds
(2) <prefix>\femalebody_1_msn\1.dds
(3) <prefix>\femalebody_1_msn\9.dds

As one can see, (1) and (2) ends up pointing to the same texture, which is, obviously, not expected behavior :(

**Comment by Piranha91** [comment]
Thanks! When it finishes uploading in a few minutes, can you check if the issues is fixed in v0.7.8.8?

**Comment by leonardovcr** [comment]
Wow that was fast :)

I'll certainly try again if I can manage to fix my SynthEBD installation. I was doing another test run on my load order (had to interrupt mid-patching after I noticed some mistakes) but now my patch runs are crashing with the following log:

SynthEBD has crashed with the following error:
An object implementing IHandleObservableErrors (often a ReactiveCommand or ObservableAsPropertyHelper) has errored, thereby breaking its observable pipeline. To prevent this, ensure the pipeline does not error, or Subscribe to the ThrownExceptions property of the object in question to handle the erroneous case.
   at ReactiveUI.RxApp.<>c__DisplayClass9_0.<.cctor>b__2() in /_/src/ReactiveUI/RxApp.cs:line 109
   at System.Reactive.Concurrency.Scheduler.Invoke(Action action) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 253
   at System.Reactive.Concurrency.Scheduler.<>c.<Schedule>b__74_0(IScheduler _, Action a) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 37
   at System.Reactive.Concurrency.DispatcherScheduler.<>c__DisplayClass12_0`1.<Schedule>b__0() in /_/src/ReactiveUI.Uwp/Rx/Concurrency/DispatcherScheduler.cs:line 98
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

An item with the same key has already been added. Key: 004510:Populated Cities Towns Villages Legendary.esp
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at SynthEBD.VM_ConsistencyUI.DumpViewModelsToModels(ObservableCollection`1 viewModels, Dictionary`2 models) in D:\a\SynthEBD\SynthEBD\SynthEBD\Settings\Settings_Consistency\VM_ConsistencyUI.cs:line 115
   at SynthEBD.SaveLoader.DumpViewModelsToModels() in D:\a\SynthEBD\SynthEBD\SynthEBD\SaveLoader.cs:line 155
   at SynthEBD.VM_RunButton.<>c__DisplayClass2_0.<<-ctor>b__0>d.MoveNext() in D:\a\SynthEBD\SynthEBD\SynthEBD\RunButton\VM_RunButton.cs:line 45

Settings also are not being persisted anymore. SynthEBD logs the following when I quit the app:

SynthEBD has crashed with the following error:
An item with the same key has already been added. Key: 004510:Populated Cities Towns Villages Legendary.esp
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at SynthEBD.VM_ConsistencyUI.DumpViewModelsToModels(ObservableCollection`1 viewModels, Dictionary`2 models) in D:\a\SynthEBD\SynthEBD\SynthEBD\Settings\Settings_Consistency\VM_ConsistencyUI.cs:line 115
   at SynthEBD.SaveLoader.DumpViewModelsToModels() in D:\a\SynthEBD\SynthEBD\SynthEBD\SaveLoader.cs:line 155
   at SynthEBD.SaveLoader.FinalClosing() in D:\a\SynthEBD\SynthEBD\SynthEBD\SaveLoader.cs:line 161
   at SynthEBD.MainWindow_ViewModel.MainWindow_Closing(Object sender, CancelEventArgs e) in D:\a\SynthEBD\SynthEBD\SynthEBD\MainWindow_ViewModel.cs:line 57
   at System.Windows.Window.OnClosing(CancelEventArgs e)
   at MahApps.Metro.Controls.MetroWindow.<>n__0(CancelEventArgs e)
   at MahApps.Metro.Controls.MetroWindow.OnClosing(CancelEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by leonardovcr** [comment]
So, I've managed to fix my installation. Had to remove "Consistency" and "Specific NPC Assignments" files... I have no idea what the problem was.

But anyway, running the asset pack import on v.0.7.8.8 fixed the texture problem! Thank you :)
