### ISSUE TITLE
0.7.8.9 crash

### ISSUE THREAD

**Issue by Myoufer** [Synthesis-Collective/SynthEBD#43]
SynthEBD has crashed with the following error:
An object implementing IHandleObservableErrors (often a ReactiveCommand or ObservableAsPropertyHelper) has errored, thereby breaking its observable pipeline. To prevent this, ensure the pipeline does not error, or Subscribe to the ThrownExceptions property of the object in question to handle the erroneous case.
   at ReactiveUI.RxApp.<>c__DisplayClass9_0.<.cctor>b__2() in /_/src/ReactiveUI/RxApp.cs:line 109
   at System.Reactive.Concurrency.Scheduler.Invoke(Action action) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 253
   at System.Reactive.Concurrency.Scheduler.<>c.<Schedule>b__74_0(IScheduler _, Action a) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 37
   at System.Reactive.Concurrency.DispatcherScheduler.<>c__DisplayClass12_0`1.<Schedule>b__0() in /_/src/ReactiveUI.Uwp/Rx/Concurrency/DispatcherScheduler.cs:line 98
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Could not find a part of the path 'C:\Users\Username\AppData\Local\ModOrganizer\Skyrim Special Edition\mods\SynthEBD Output\SynthEBD'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetFiles(String path, String searchPattern, EnumerationOptions enumerationOptions)
   at System.IO.Directory.GetFiles(String path)
   at SynthEBD.HeadPartPreprocessing.CleanPreviousOutputs() in D:\a\SynthEBD\SynthEBD\SynthEBD\Patcher\Head Part Patching\HeadPartPreprocessing.cs:line 14
   at SynthEBD.Patcher.RunPatcher() in D:\a\SynthEBD\SynthEBD\SynthEBD\Patcher\Patcher.cs:line 175
   at SynthEBD.VM_RunButton.<>c__DisplayClass2_0.<<-ctor>b__0>d.MoveNext() in D:\a\SynthEBD\SynthEBD\SynthEBD\RunButton\VM_RunButton.cs:line 49

Patcher Settings Creation Log:
Found settings source path at C:\Modding\SynthEBD_v0.7.8.9\Settings\SettingsSource.json
Source Settings: 
Skyrim Version: SkyrimSE
Game Environment Directory: 
Load Settings from Portable Folder: False
Portable Folder Location: 

Patcher Environment Creation Log:
Creating Patcher Environment:
Output mod: SynthEBD.esp
Skyrim Version: SkyrimSE
Game Data Directory: Default
Environment created successfully
Creating Patcher Environment:
Output mod: SynthEBD.esp
Skyrim Version: SkyrimSE
Game Data Directory: Default
Environment created successfully

**Comment by Myoufer** [comment]
Duplicate of #42
