### ISSUE TITLE
SynthEBD fails to patch after purging "SynthEBD_output" contents

### ISSUE THREAD

**Issue by leonardovcr** [Synthesis-Collective/SynthEBD#44]
Hi again,

As the title says, I'm trying to run the patcher after deleting all the content inside C:\Modding\MO2\mods\SynthEBD_output, and now it just won't patch anything anymore :(

The patcher fails with:

SynthEBD has crashed with the following error:
An object implementing IHandleObservableErrors (often a ReactiveCommand or ObservableAsPropertyHelper) has errored, thereby breaking its observable pipeline. To prevent this, ensure the pipeline does not error, or Subscribe to the ThrownExceptions property of the object in question to handle the erroneous case.
   at ReactiveUI.RxApp.<>c__DisplayClass9_0.<.cctor>b__2() in /_/src/ReactiveUI/RxApp.cs:line 109
   at System.Reactive.Concurrency.Scheduler.Invoke(Action action) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 253
   at System.Reactive.Concurrency.Scheduler.<>c.<Schedule>b__74_0(IScheduler _, Action a) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 37
   at System.Reactive.Concurrency.DispatcherScheduler.<>c__DisplayClass12_0`1.<Schedule>b__0() in /_/src/ReactiveUI.Uwp/Rx/Concurrency/DispatcherScheduler.cs:line 98
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Could not find a part of the path 'C:\Modding\MO2\mods\SynthEBD_output\SynthEBD'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetFiles(String path, String searchPattern, EnumerationOptions enumerationOptions)
   at System.IO.Directory.GetFiles(String path)
   at SynthEBD.HeadPartPreprocessing.CleanPreviousOutputs() in D:\a\SynthEBD\SynthEBD\SynthEBD\Patcher\Head Part Patching\HeadPartPreprocessing.cs:line 14
   at SynthEBD.Patcher.RunPatcher() in D:\a\SynthEBD\SynthEBD\SynthEBD\Patcher\Patcher.cs:line 175
   at SynthEBD.VM_RunButton.<>c__DisplayClass2_0.<<-ctor>b__0>d.MoveNext() in D:\a\SynthEBD\SynthEBD\SynthEBD\RunButton\VM_RunButton.cs:line 49

Patcher Settings Creation Log:
Found settings source path at C:\Modding\MO2\SynthEBD_v0.7.8.9\Settings\SettingsSource.json
Source Settings: 
Skyrim Version: SkyrimSE
Game Environment Directory: 
Load Settings from Portable Folder: False
Portable Folder Location: 

Patcher Environment Creation Log:
Creating Patcher Environment:
Output mod: SynthEBD.esp
Skyrim Version: SkyrimSE
Game Data Directory: Default
Environment created successfully
Creating Patcher Environment:
Output mod: SynthEBD.esp
Skyrim Version: SkyrimSE
Game Data Directory: Default
Environment created successfully

The patcher actually manages to create three directories (SKSE, Seq, Scripts) and one file (SynthEBDHeadPartDistributor_DISTR), but stops there :(

**Comment by leonardovcr** [comment]
Found a workaround: manually create the folder "SynthEBD" inside "SynthEBD_output"...

Maybe it's a MO2 issue? I have "create files in mod instead of overwrite" enabled already.

**Comment by Piranha91** [comment]
Nope, not an MO2 issue, is the same issue that Inokentych posted yesterday. Sorry, I’m aware of the issue, will be patched in the next release. In the meantime, manually creating the directory as you did will remedy the crash. I’ll try to have the fixed release or tomorrow.

**Comment by leonardovcr** [comment]
Now I'm trying to import an asset pack from an archive, and again having file access problems. I tracked this problem down to Windows 10 built-in antivirus being a major inconvenience again. All my folders are read-only for some reason. Changing to read-write doesn't work because Windows immediatly reverts the changes. Tomorrow I'll try to investigate this issue further...

**Comment by Inokentych** [comment]
> All my folders are read-only for some reason. Changing to read-write doesn't work because Windows immediatly reverts the changes. Tomorrow I'll try to investigate this issue further...
My issue was that SynthEBD not want write esp in folder where i want but today i fixed problem, not sure what it was but i played with win10 setting "secure folder access" toggle on/off and after that tried make esp and not have write failed anymore, so maybe this help for your problem.

**Comment by Piranha91** [comment]
The crash related to the missing SynthEBD folder should be fixed in v0.8.0! Not sure what's going on with the file access issues; I haven't had any trouble on my end. Could be rogue antivirus?

**Comment by leonardovcr** [comment]
V0.8.0 fixed the output folder crash :)

As Inokentych said, "secure folder access" was the culprit. Now read/write is going well again. How I hate Windows...
