### ISSUE TITLE
IHandleObservableErrors issues prevent patcher from running

### ISSUE THREAD

**Issue by Lavapulse** [Synthesis-Collective/SynthEBD#55]
Error received is as follows:

SynthEBD has crashed with the following error:
An object implementing IHandleObservableErrors (often a ReactiveCommand or ObservableAsPropertyHelper) has errored, thereby breaking its observable pipeline. To prevent this, ensure the pipeline does not error, or Subscribe to the ThrownExceptions property of the object in question to handle the erroneous case.
   at ReactiveUI.RxApp.<>c__DisplayClass9_0.<.cctor>b__2() in /_/src/ReactiveUI/RxApp.cs:line 109
   at System.Reactive.Concurrency.Scheduler.Invoke(Action action) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 253
   at System.Reactive.Concurrency.Scheduler.<>c.<Schedule>b__74_0(IScheduler _, Action a) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 37
   at System.Reactive.Concurrency.DispatcherScheduler.<>c__DisplayClass12_0`1.<Schedule>b__0() in /_/src/ReactiveUI.Uwp/Rx/Concurrency/DispatcherScheduler.cs:line 96
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Object reference not set to an instance of an object.
   at SynthEBD.HeightPatcher.AssignRacialHeight(HeightConfig heightConfig, SkyrimMod outputMod) in C:\Users\[NameRemoved]\AppData\Local\Temp\Synthesis\hzi5ovyv.yif\Git\luvlwyln.5v2\Runner\SynthEBD\Patcher\Height Patching\HeightPatcher.cs:line 0
   at SynthEBD.Patcher.RunPatcher() in C:\Users\[NameRemoved]\AppData\Local\Temp\Synthesis\hzi5ovyv.yif\Git\luvlwyln.5v2\Runner\SynthEBD\Patcher\Patcher.cs:line 132
   at SynthEBD.VM_RunButton.<>c__DisplayClass2_0.<<-ctor>b__0>d.MoveNext() in C:\Users\[NameRemoved]\AppData\Local\Temp\Synthesis\hzi5ovyv.yif\Git\luvlwyln.5v2\Runner\SynthEBD\RunButton\VM_RunButton.cs:line 49

Patcher Settings Creation Log:
Found settings source path at C:\Users\[NameRemoved]\AppData\Local\Temp\Synthesis\hzi5ovyv.yif\Git\luvlwyln.5v2\Runner\SynthEBD\bin\Release\net6.0-windows\win-x64\Settings\SettingsSource.json
Source Settings: 
Skyrim Version: SkyrimSE
Game Environment Directory: 
Load Settings from Portable Folder: True
Portable Folder Location: D:\Modding\Skyrim\Wabbajack\install\mods\Synthesis Output\SynthEBD

Patcher Environment Creation Log:
Creating Patcher Environment:
Output mod: SynthEBD.esp
Skyrim Version: SkyrimSE
Game Data Directory: Default
Environment created successfully
Creating Patcher Environment:
Output mod: SynthEBD.esp
Skyrim Version: SkyrimSE
Game Data Directory: Default
Environment created successfully

**Comment by Piranha91** [comment]
I'll have to do some digging because I don't immediately see why it would crash here, but I do notice your Portable Folder Location is set to Synthesis Output\SynthEBD. I don't think that would directly lead to conflicts but it's a bit unexpected; the portable folder is supposed to be where your settings files live rather than your output. If you go to that folder, is there a SynthEBD\Height Configurations\Default Config.json?

**Comment by Lavapulse** [comment]
Ah, I wish I'd seen this sooner. I'd already happened to change the configuration to separate the config and output into their own destinations because I also suspected that might be the issue, so unfortunately I can't tell you whether the config files were properly placed before.

Currently, the structure looks correct as far as I can tell.

![image](https://user-images.githubusercontent.com/50252900/191718814-612d115e-80ef-41d4-b7c9-ed792c94c539.png)

(My SynthEBD Output directory currently remains empty).

Unfortunately, I'm still receiving the same error:

> SynthEBD has crashed with the following error:
An object implementing IHandleObservableErrors (often a ReactiveCommand or ObservableAsPropertyHelper) has errored, thereby breaking its observable pipeline. To prevent this, ensure the pipeline does not error, or Subscribe to the ThrownExceptions property of the object in question to handle the erroneous case.
   at ReactiveUI.RxApp.<>c__DisplayClass9_0.<.cctor>b__2() in /_/src/ReactiveUI/RxApp.cs:line 109
   at System.Reactive.Concurrency.Scheduler.Invoke(Action action) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 253
   at System.Reactive.Concurrency.Scheduler.<>c.<Schedule>b__74_0(IScheduler _, Action a) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 37
   at System.Reactive.Concurrency.DispatcherScheduler.<>c__DisplayClass12_0`1.<Schedule>b__0() in /_/src/ReactiveUI.Uwp/Rx/Concurrency/DispatcherScheduler.cs:line 98
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

>Object reference not set to an instance of an object.
   at SynthEBD.HeightPatcher.AssignRacialHeight(HeightConfig heightConfig, SkyrimMod outputMod) in D:\a\SynthEBD\SynthEBD\SynthEBD\Patcher\Height Patching\HeightPatcher.cs:line 0
   at SynthEBD.Patcher.RunPatcher() in D:\a\SynthEBD\SynthEBD\SynthEBD\Patcher\Patcher.cs:line 132
   at SynthEBD.VM_RunButton.<>c__DisplayClass2_0.<<-ctor>b__0>d.MoveNext() in D:\a\SynthEBD\SynthEBD\SynthEBD\RunButton\VM_RunButton.cs:line 49

>Patcher Settings Creation Log:
Found settings source path at D:\Games\Steam\steamapps\common\Skyrim Special Edition\data\Settings\SettingsSource.json
Source Settings: 
Skyrim Version: SkyrimSE
Game Environment Directory: 
Load Settings from Portable Folder: True
Portable Folder Location: D:\Modding\Skyrim\Wabbajack\install\mods\SynthEBD Config\SynthEBD

>Patcher Environment Creation Log:
Creating Patcher Environment:
Output mod: SynthEBD.esp
Skyrim Version: SkyrimSE
Game Data Directory: Default
Environment created successfully
Creating Patcher Environment:
Output mod: SynthEBD.esp
Skyrim Version: SkyrimSE
Game Data Directory: Default
Environment created successfully

After browsing some of the other submissions, I can confirm that I don't have any custom races installed, and temporarily disabling Windows's antivirus didn't make a difference. In case it matters, I do have Autobody installed, which I'm using separately to manage bodyslide distribution, but that runs via SKSE in-game, so I can't imagine why it would conflict here.

**Comment by Lavapulse** [comment]
Update: I'm able to run the patcher just fine when height assignments are disabled. The height config itself is unmodified from default. I've attached it for reference.
[Default Config.txt](https://github.com/Synthesis-Collective/SynthEBD/files/9630862/Default.Config.txt)

**Comment by Piranha91** [comment]
Sorry for the delay! Should be fixed in 0.8.3 - please let me know if you still have the issue.

**Comment by Piranha91** [comment]
Closed due to inactivity.
