### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by FuzileiroGamer** [Synthesis-Collective/SynthEBD#63]
Crashing and receiving the following error: Did I do something wrong?

SynthEBD has crashed with the following error:
The invocation of the constructor on type 'SynthEBD.MainWindow' that matches the specified binding constraints threw an exception.
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Data at the root level is invalid. Line 1, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   at SynthEBD.Settings_OBody.ImportBodySlides(HashSet`1 templateDescriptors) in D:\a\SynthEBD\SynthEBD\SynthEBD\Settings\Settings_OBody\Settings_OBody.cs:line 53
   at SynthEBD.SaveLoader.LoadInitialSettingsViewModels() in D:\a\SynthEBD\SynthEBD\SynthEBD\SaveLoader.cs:line 78
   at SynthEBD.MainWindow_ViewModel.Init() in D:\a\SynthEBD\SynthEBD\SynthEBD\MainWindow_ViewModel.cs:line 46
   at SynthEBD.MainWindow..ctor() in D:\a\SynthEBD\SynthEBD\SynthEBD\MainWindow.xaml.cs:line 28
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)

**Comment by Piranha91** [comment]
It looks like one of your bodyslides is corrupted or in a format that SynthEBD isn’t set up to deal with. If you have the patience you can try disabling body slide mods and see which one is causing the issue - if you pin it down I could take a look at it.

**Comment by FuzileiroGamer** [comment]
I'll try

**Comment by FuzileiroGamer** [comment]
Ok that's was quick, in the end I'm the culprit. When you wrote about the bodyslide I had and idea already. I changed the preset names to numbers accessing VSF via Explorer++ present in MO2, so bigboobapreset.xml would be 1.xml for example, Obody recognizes it but EBD seems to have some trouble with numbers as name for the .xml files. Tested with numbers and with normal names of the presets, numbers give me the error, normal preset names don't.

**Comment by Piranha91** [comment]
But renaming the xml file doesn't rename the bodyslide, right? You would have to edit the .xml and change `<Preset name="oldname" set="whatever">` to `<Preset name="1" set="whatever">`. I just tried it and renaming both the .xml file and the name= contents didn't cause any problems, so my guess is that your xml got corrupted - maybe you forgot an end quote after the number you assigned?

**Comment by FuzileiroGamer** [comment]
now that you mention it, I did commit a mistake when renaming and forgot to account for the .xml file extension in the name file, that may have corrupted the files. I'm gonna reinstall the presets and rename them without committing the same error and see if it works properly

**Comment by FuzileiroGamer** [comment]
It works! So it's my fault for corrupting the files by changing the names without accounting for the extensions! The program is opening just fine now. Thank you for your patience!

**Comment by Piranha91** [comment]
Honestly if all you did was remove the file extension that’s on me - it should skip non-xml files. I’ll see if I can fix that.

**Comment by FuzileiroGamer** [comment]
There is nothing to fix, you got it wrong, on the first time around, renaming the files, I missed the extension so I renamed then again with the extension included to "correct" the error of renaming without the file extension, nothing related to EBD until then. This renaming again to include the file extension is what I think that broke the files. Then, days later, today, I got the error when trying to open EBD. What I did then was reinstall all my presets and rename them again, but without committing the same error of the first time around. I do believe it was My fault because of the error I committed on the first time renaming the files. You may look into it but I don't think you will find anything wrong with EBD on this regard. Sorry for broken english, it's not my first language.
