### ISSUE TITLE
Feature request... sort entries alphabetically

### ISSUE THREAD

**Issue by leonardovcr** [Synthesis-Collective/SynthEBD#64]
Hi again,

I wonder if it would be possible to implement some kind of sort routine for some entries in SynthEBD... Specifically, BodySlide, Block List, Specific NPC Assignments and Attribute Groups records.

It's getting harder and harder to find some specific NPC or bodyslide when the list gets bigger or when some new additions are made. For example, if I have some 30 specific NPC asignments and add a new npc (for example, Aela) it goes to the end of the list, which is not much intuitive...

Maybe a "sort button" somewhere?

Thanks!

**Comment by Piranha91** [comment]
That's a good idea, and should be easy enough to implement. I'll see if I can get it into the next version.

**Comment by Piranha91** [comment]
Added this in 0.8.4.2 (AZ button). I think I missed that you wanted it in Attribute Groups - I can add it there in the next release.

**Comment by leonardovcr** [comment]
Hi Piranha, just a heads up... There's a weird behaviour going on with the Specific NPC Assignments sorted list. If I add a new entry, and then sort the list without saving it first, that new entry vanishes and becomes another entry with a new NPC on the list.

**Comment by Piranha91** [comment]
Hmm, having trouble replicating, unless I'm misunderstanding. This is what it does for me

https://i.imgur.com/dj5y1o3.gif

**Comment by leonardovcr** [comment]
Yeah, just launched SynthEBD again, and I'm also unable to replicate it anymore...  After adding and sorting without saving, clicking on a previously added npc entry would replace the newly added entry with another already added npc.

The problem happened during a session where I was managing and adding dozens of specific NPC entries for quite some time, and each click would take some good 2-3 seconds to respond. I'm not sure if it could be a bug related to entries already added before the feature, or something related to SynthEBD's lagginess that always happens after extended usage time, or even the large quantity of npc's I was managing.

Anyway, I'll try to make a video of it when/if it happens again...

**Comment by leonardovcr** [comment]
Well, now I've just got a random error message after launching SynthEBD:

SynthEBD has crashed with the following error:
Object reference not set to an instance of an object.
   at SynthEBD.VM_SpecificNPCAssignmentsUI.<>c.<.ctor>b__0_10(VM_SpecificNPCAssignment x) in D:\a\SynthEBD\SynthEBD\SynthEBD\Settings\Settings_SpecificNPCAssignments\VM_SpecificNPCAssignmentsUI.cs:line 114
   at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)
   at System.Linq.OrderedEnumerable`1.ToList()
   at SynthEBD.ObservableCollection.IsSorted[TSource,TKey](ObservableCollection`1 source, Func`2 keySelector, Boolean reverse) in D:\a\SynthEBD\SynthEBD\SynthEBD\GUI_Aux\ObservableCollectionSorter.cs:line 29
   at SynthEBD.VM_Alphabetizer`2.GetSortState() in D:\a\SynthEBD\SynthEBD\SynthEBD\Classes_Aux\ViewModels\VM_Alphabetizer.cs:line 90
   at SynthEBD.VM_Alphabetizer`2.<.ctor>b__36_4(IChangeSet`1 x) in D:\a\SynthEBD\SynthEBD\SynthEBD\Classes_Aux\ViewModels\VM_Alphabetizer.cs:line 42
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 54
   at System.Reactive.Linq.ObservableImpl.Throttle`1._.Propagate(UInt64 currentid) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Throttle.cs:line 77
   at System.Reactive.Linq.ObservableImpl.Throttle`1._.<>c.<OnNext>b__9_0(ValueTuple`2 tuple) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Throttle.cs:line 68
   at System.Reactive.Concurrency.Scheduler.Invoke[TState](ValueTuple`2 tuple) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 259
   at System.Reactive.Concurrency.Scheduler.<>c__78`1.<ScheduleAction>b__78_0(IScheduler _, ValueTuple`2 tuple) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 137
   at System.Reactive.Concurrency.DispatcherScheduler.<>c__DisplayClass14_0`1.<ScheduleSlow>b__0(Object s, EventArgs e) in /_/src/ReactiveUI.Uwp/Rx/Concurrency/DispatcherScheduler.cs:line 145
   at System.Windows.Threading.DispatcherTimer.FireTick()
   at System.Windows.Threading.DispatcherTimer.<>c.<Restart>b__21_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)



Patcher Settings Creation Log:
Found settings source path at C:\Modding\MO2\SynthEBD_v0.8.4.2\Settings\SettingsSource.json
Source Settings: 
Skyrim Version: SkyrimSE
Game Environment Directory: 
Load Settings from Portable Folder: False
Portable Folder Location: 


Patcher Environment Creation Log:
Creating Patcher Environment:
Output mod: SynthEBD.esp
Skyrim Version: SkyrimSE
Game Data Directory: Default
Environment created successfully
Creating Patcher Environment:
Output mod: SynthEBD.esp
Skyrim Version: SkyrimSE
Game Data Directory: Default
Environment created successfully

Seems to be related to the Specific NPC's list. Error message aside, patcher is working fine

**Comment by Piranha91** [comment]
Mind sharing your specific NPC assignments json file?

**Comment by leonardovcr** [comment]
Sure, no problem: 
[Specific NPC Assignments.zip](https://github.com/Synthesis-Collective/SynthEBD/files/10191313/Specific.NPC.Assignments.zip)

**Comment by Piranha91** [comment]
The crashing issue should be fixed, and alphabetizer added to Attribute Groups, in 0.8.5.

**Comment by leonardovcr** [comment]
Thanks!
