### ISSUE TITLE
Crash with new version 0.8.6

### ISSUE THREAD

**Issue by Gawdzila** [Synthesis-Collective/SynthEBD#71]
Here's the crash log.  It crashes whenever I run the patcher.  It seems to patch for just a second and throws a few of the normal "No valid asset packs could be found for NPC XXX", then it throws the error window.  Interestingly, the Patching timer keeps running but nothing is happening in the log.  Let me know if you need anything else!

SynthEBD has crashed with the following error:
An object implementing IHandleObservableErrors (often a ReactiveCommand or ObservableAsPropertyHelper) has errored, thereby breaking its observable pipeline. To prevent this, ensure the pipeline does not error, or Subscribe to the ThrownExceptions property of the object in question to handle the erroneous case.
   at ReactiveUI.RxApp.<>c__DisplayClass9_0.<.cctor>b__2() in /_/src/ReactiveUI/RxApp.cs:line 109
   at System.Reactive.Concurrency.Scheduler.Invoke(Action action) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 253
   at System.Reactive.Concurrency.Scheduler.<>c.<Schedule>b__74_0(IScheduler _, Action a) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 37
   at System.Reactive.Concurrency.DispatcherScheduler.<>c__DisplayClass12_0`1.<Schedule>b__0() in /_/src/ReactiveUI.Uwp/Rx/Concurrency/DispatcherScheduler.cs:line 98
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Object reference not set to an instance of an object.
   at SynthEBD.FacePartCompliance.CheckAndFixFaceName(NPCInfo npcInfo, ILinkCache linkCache, SkyrimMod outputMod) in D:\a\SynthEBD\SynthEBD\SynthEBD\Patcher\PatcherAux\FacePartCompliance.cs:line 37
   at SynthEBD.Patcher.MainLoop(IEnumerable`1 npcCollection, Boolean skipLinkedSecondaryNPCs, SkyrimMod outputMod, CategorizedFlattenedAssetPacks sortedAssetPacks, BodyGenConfigs bodyGenConfigs, Settings_OBody oBodySettings, HeightConfig currentHeightConfig, Settings_Headparts headPartSettings, Int32 npcCounter, HashSet`1 generatedLinkGroups, HashSet`1 skippedLinkedNPCs, Keyword EBDFaceKW, Keyword EBDScriptKW, FacePartCompliance facePartComplianceMaintainer, HashSet`1 headPartNPCs) in D:\a\SynthEBD\SynthEBD\SynthEBD\Patcher\Patcher.cs:line 562
   at SynthEBD.Patcher.RunPatcher() in D:\a\SynthEBD\SynthEBD\SynthEBD\Patcher\Patcher.cs:line 207
   at SynthEBD.VM_RunButton.<>c__DisplayClass2_0.<<-ctor>b__0>d.MoveNext() in D:\a\SynthEBD\SynthEBD\SynthEBD\RunButton\VM_RunButton.cs:line 49

Patcher Settings Creation Log:
Found settings source path at I:\Game Mods\Skyrim SE Mods\Tools\SynthEBD\Settings\SettingsSource.json
Source Settings: 
Skyrim Version: SkyrimVR
Game Environment Directory: 
Load Settings from Portable Folder: False
Portable Folder Location: 

Patcher Environment Creation Log:
Creating Patcher Environment:
Output mod: SynthEBD.esp
Skyrim Version: SkyrimVR
Game Data Directory: Default
Environment created successfully
Creating Patcher Environment:
Output mod: SynthEBD.esp
Skyrim Version: SkyrimVR
Game Data Directory: Default
Environment created successfully_

**Comment by Piranha91** [comment]
Should hopefully be fixed in 0.8.6.1. Let me know if that doesn't fix the issue.

**Comment by Gawdzila** [comment]
Hey!

Sorry I didn't get back to this earlier, the holidays were busy and I didn't get back to playing until this past weekend.  I tried to update to newer versions to solve the other issue I submitted, but unfortunately it doesn't look like the later versions solved this crash for me so I can't use them.  I tried both 0.8.6.1 and .2.  This is the error message from 0.8.6.2:

```
SynthEBD has crashed with the following error:
An object implementing IHandleObservableErrors (often a ReactiveCommand or ObservableAsPropertyHelper) has errored, thereby breaking its observable pipeline. To prevent this, ensure the pipeline does not error, or Subscribe to the ThrownExceptions property of the object in question to handle the erroneous case.
   at ReactiveUI.RxApp.<>c__DisplayClass9_0.<.cctor>b__2() in /_/src/ReactiveUI/RxApp.cs:line 109
   at System.Reactive.Concurrency.Scheduler.Invoke(Action action) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 253
   at System.Reactive.Concurrency.Scheduler.<>c.<Schedule>b__74_0(IScheduler _, Action a) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 37
   at System.Reactive.Concurrency.DispatcherScheduler.<>c__DisplayClass12_0`1.<Schedule>b__0() in /_/src/ReactiveUI.Uwp/Rx/Concurrency/DispatcherScheduler.cs:line 98
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Object reference not set to an instance of an object.
   at SynthEBD.FacePartCompliance.CheckAndFixFaceName(NPCInfo npcInfo, ILinkCache linkCache, SkyrimMod outputMod) in D:\a\SynthEBD\SynthEBD\SynthEBD\Patcher\PatcherAux\FacePartCompliance.cs:line 42
   at SynthEBD.Patcher.MainLoop(IEnumerable`1 npcCollection, Boolean skipLinkedSecondaryNPCs, SkyrimMod outputMod, CategorizedFlattenedAssetPacks sortedAssetPacks, BodyGenConfigs bodyGenConfigs, Settings_OBody oBodySettings, HeightConfig currentHeightConfig, Settings_Headparts headPartSettings, Int32 npcCounter, HashSet`1 generatedLinkGroups, HashSet`1 skippedLinkedNPCs, Keyword EBDFaceKW, Keyword EBDScriptKW, FacePartCompliance facePartComplianceMaintainer, HashSet`1 headPartNPCs) in D:\a\SynthEBD\SynthEBD\SynthEBD\Patcher\Patcher.cs:line 562
   at SynthEBD.Patcher.RunPatcher() in D:\a\SynthEBD\SynthEBD\SynthEBD\Patcher\Patcher.cs:line 207
   at SynthEBD.VM_RunButton.<>c__DisplayClass2_0.<<-ctor>b__0>d.MoveNext() in D:\a\SynthEBD\SynthEBD\SynthEBD\RunButton\VM_RunButton.cs:line 49



Patcher Settings Creation Log:
Found settings source path at I:\Game Mods\Skyrim SE Mods\Tools\SynthEBD\Settings\SettingsSource.json
Source Settings: 
Skyrim Version: SkyrimVR
Game Environment Directory: 
Load Settings from Portable Folder: False
Portable Folder Location: 


Patcher Environment Creation Log:
Creating Patcher Environment:
Output mod: SynthEBD.esp
Skyrim Version: SkyrimVR
Game Data Directory: Default
Environment created successfully
Creating Patcher Environment:
Output mod: SynthEBD.esp
Skyrim Version: SkyrimVR
Game Data Directory: Default
Environment created successfully
```

**Comment by Piranha91** [comment]
Hmm ok - hang tight for just a bit. In a few days I’m hoping to release 0.9 - I redid pretty much all of the internal wiring over the holiday, we’ll see if it helped. If not we can continue troubleshooting.

**Comment by Piranha91** [comment]
Sorry for the delay - give 0.9 a shot (if it still doesn't work as standalone, try running through Synthesis - it would be informative to know which mode works, if either).

**Comment by Gawdzila** [comment]
At first glance I thought I had a different error so I created a new issue, but my eyeballs must be broken -- actually it seems like I'm getting the same crash in 0.9.2 as with the older 0.8.6+ releases.  It makes me wonder if there's something weird about my configs, or settings, but it seems to work fine in 0.8.5.
