### ISSUE TITLE
Crash while deleting multiple asset packs in a row

### ISSUE THREAD

**Issue by leonardovcr** [Synthesis-Collective/SynthEBD#86]
This happened after I renamed 4 asset packs and tried deleting them afterwards. It crashed after the last one. Here's the stack dump:

```
SynthEBD has crashed with the following error:
Object reference not set to an instance of an object.
   at SynthEBD.VM_AssetPresenter.UpdatePreviewImages(VM_AssetPack source) in D:\a\SynthEBD\SynthEBD\SynthEBD\Classes_Aux\ViewModels\VM_AssetPresenter.cs:line 58
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)



Patcher Settings Creation Log:
Found settings source path at C:\Modding\MO2\SynthEBD_v0.9.0.2-vanilla\Settings\SettingsSource.json
Source Settings: 
Load Settings from Portable Folder: False
Portable Folder Location: 


Patcher Environment Creation Log:
Found environment source path at C:\Modding\MO2\SynthEBD_v0.9.0.2-vanilla\Settings\EnvironmentSource.json
Source Settings: 
Skyrim Version: SkyrimSE
Game Environment Directory: C:\program files (x86)\steam\steamapps\common\Skyrim Special Edition\Data
```

**Comment by Piranha91** [comment]
I wasn't able to reproduce this but I added a null check in the line reported in your crash log - let me know if the issue persists in 0.9.1.

**Comment by leonardovcr** [comment]
I think we can close this issue, I haven't got a crash for a few days now... thanks.
