### ISSUE TITLE
Crash while running patcher

### ISSUE THREAD

**Issue by leonardovcr** [Synthesis-Collective/SynthEBD#87]
Another crash, this time while running patcher. Happens sometimes... not always:

```
SynthEBD has crashed with the following error:
Destination array was not long enough. Check the destination index, length, and the array's lower bounds. (Parameter 'destinationArray')
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length)
   at System.Collections.Generic.List`1.CopyTo(T[] array, Int32 arrayIndex)
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at SynthEBD.VM_LogDisplay.<.ctor>b__28_0(IChangeSet`1 x) in D:\a\SynthEBD\SynthEBD\SynthEBD\GUI_Aux\ViewModels\VM_LogDisplay.cs:line 36
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 54
   at System.Reactive.Linq.ObservableImpl.Throttle`1._.Propagate(UInt64 currentid) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Throttle.cs:line 82
   at System.Reactive.Concurrency.Scheduler.<>c__78`1.<ScheduleAction>b__78_0(IScheduler _, ValueTuple`2 tuple) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 137
   at System.Reactive.Concurrency.DispatcherScheduler.<>c__DisplayClass14_0`1.<ScheduleSlow>b__0(Object s, EventArgs e) in /_/src/ReactiveUI.Uwp/Rx/Concurrency/DispatcherScheduler.cs:line 153
   at System.Windows.Threading.DispatcherTimer.FireTick()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by Piranha91** [comment]
I wasn't able to reproduce this but I tweaked the line reported in your crash log.  Let me know if the issue persists in 0.9.1.

**Comment by leonardovcr** [comment]
No crash while running patcher so far... I think we can close the issue, thanks again.
