### ISSUE TITLE
IHandleObservableErrors Crash During Patch

### ISSUE THREAD

**Issue by Gawdzila** [Synthesis-Collective/SynthEBD#93]
I compared the message and I don't think it's the same crash as the issue below.  I got this when running the patcher:

```
SynthEBD has crashed with the following error:
An object implementing IHandleObservableErrors (often a ReactiveCommand or ObservableAsPropertyHelper) has errored, thereby breaking its observable pipeline. To prevent this, ensure the pipeline does not error, or Subscribe to the ThrownExceptions property of the object in question to handle the erroneous case.
   at ReactiveUI.RxApp.<>c__DisplayClass9_0.<.cctor>b__2() in /_/src/ReactiveUI/RxApp.cs:line 109
   at System.Reactive.Concurrency.Scheduler.Invoke(Action action) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 253
   at System.Reactive.Concurrency.Scheduler.<>c.<Schedule>b__74_0(IScheduler _, Action a) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 37
   at System.Reactive.Concurrency.DispatcherScheduler.<>c__DisplayClass12_0`1.<Schedule>b__0() in /_/src/ReactiveUI.Uwp/Rx/Concurrency/DispatcherScheduler.cs:line 96
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Object reference not set to an instance of an object.
   at SynthEBD.FacePartCompliance.CheckAndFixFaceName(NPCInfo npcInfo, ILinkCache linkCache, ISkyrimMod outputMod) in D:\a\SynthEBD\SynthEBD\SynthEBD\Patcher\PatcherAux\FacePartCompliance.cs:line 42
   at SynthEBD.Patcher.MainLoop(IEnumerable`1 npcCollection, Boolean skipLinkedSecondaryNPCs, ISkyrimMod outputMod, CategorizedFlattenedAssetPacks sortedAssetPacks, BodyGenConfigs bodyGenConfigs, Settings_OBody oBodySettings, HeightConfig currentHeightConfig, Settings_Headparts headPartSettings, HashSet`1 generatedLinkGroups, HashSet`1 skippedLinkedNPCs, Keyword EBDFaceKW, Keyword EBDScriptKW, FacePartCompliance facePartComplianceMaintainer, HashSet`1 headPartNPCs) in D:\a\SynthEBD\SynthEBD\SynthEBD\Patcher\Patcher.cs:line 648
   at SynthEBD.Patcher.RunPatcher() in D:\a\SynthEBD\SynthEBD\SynthEBD\Patcher\Patcher.cs:line 278
   at SynthEBD.VM_RunButton.<>c__DisplayClass7_0.<<-ctor>b__0>d.MoveNext() in D:\a\SynthEBD\SynthEBD\SynthEBD\RunButton\VM_RunButton.cs:line 76



Patcher Settings Creation Log:
Found settings source path at I:\Game Mods\Skyrim SE Mods\Tools\SynthEBD\Settings\SettingsSource.json
Source Settings: 
Load Settings from Portable Folder: False
Portable Folder Location: 


Patcher Environment Creation Log:
Found environment source path at I:\Game Mods\Skyrim SE Mods\Tools\SynthEBD\Settings\EnvironmentSource.json
Source Settings: 
Skyrim Version: SkyrimVR
Game Environment Directory: D:\Bethesda\Skyrim VR\Data
```

**Comment by Piranha91** [comment]
I think I should have this fixed in 0.9.3 - please let me know if it still crashes.

**Comment by matashina** [comment]
Hey, I'm also getting this with 0.9.3.1, but with a somewhat different stack trace:

```
SynthEBD has crashed with the following error:
An object implementing IHandleObservableErrors (often a ReactiveCommand or ObservableAsPropertyHelper) has errored, thereby breaking its observable pipeline. To prevent this, ensure the pipeline does not error, or Subscribe to the ThrownExceptions property of the object in question to handle the erroneous case.
   at ReactiveUI.RxApp.<>c__DisplayClass9_0.<.cctor>b__2() in /_/src/ReactiveUI/RxApp.cs:line 109
   at System.Reactive.Concurrency.Scheduler.Invoke(Action action) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 253
   at System.Reactive.Concurrency.Scheduler.<>c.<Schedule>b__74_0(IScheduler _, Action a) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 37
   at System.Reactive.Concurrency.DispatcherScheduler.<>c__DisplayClass12_0`1.<Schedule>b__0() in /_/src/ReactiveUI.Uwp/Rx/Concurrency/DispatcherScheduler.cs:line 98
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Object reference not set to an instance of an object.
   at SynthEBD.AssetAndBodyShapeSelector.GenerateCombinationWithBodyShape(HashSet`1 availableAssetPacks, BodyGenConfigs bodyGenConfigs, Settings_OBody oBodySettings, AssetAndBodyShapeAssignment assignment, NPCInfo npcInfo, Boolean blockBodyShape, AssetPackAssignmentMode mode, AssetAndBodyShapeAssignment currentAssignments, List`1 previousAssignments) in D:\a\SynthEBD\SynthEBD\SynthEBD\Patcher\Shared\AssetAndBodyShapeSelector.cs:line 377
   at SynthEBD.AssetAndBodyShapeSelector.ChooseCombinationAndBodyShape(Boolean& assetsAssigned, Boolean& bodyShapeAssigned, HashSet`1 availableAssetPacks, BodyGenConfigs bodyGenConfigs, Settings_OBody oBodySettings, NPCInfo npcInfo, Boolean blockBodyShape, AssetPackAssignmentMode mode, AssetAndBodyShapeAssignment currentAssignments, List`1 previousAssignments, Boolean& mixInDeclined) in D:\a\SynthEBD\SynthEBD\SynthEBD\Patcher\Shared\AssetAndBodyShapeSelector.cs:line 194
   at SynthEBD.Patcher.MainLoop(IEnumerable`1 npcCollection, Boolean skipLinkedSecondaryNPCs, ISkyrimMod outputMod, CategorizedFlattenedAssetPacks sortedAssetPacks, BodyGenConfigs bodyGenConfigs, Settings_OBody oBodySettings, HeightConfig currentHeightConfig, Settings_Headparts headPartSettings, HashSet`1 generatedLinkGroups, HashSet`1 skippedLinkedNPCs, Keyword EBDFaceKW, Keyword EBDScriptKW, FacePartCompliance facePartComplianceMaintainer, HashSet`1 headPartNPCs) in D:\a\SynthEBD\SynthEBD\SynthEBD\Patcher\Patcher.cs:line 492
   at SynthEBD.Patcher.RunPatcher() in D:\a\SynthEBD\SynthEBD\SynthEBD\Patcher\Patcher.cs:line 278
   at SynthEBD.VM_RunButton.<>c__DisplayClass7_0.<<-ctor>b__0>d.MoveNext() in D:\a\SynthEBD\SynthEBD\SynthEBD\RunButton\VM_RunButton.cs:line 76



Patcher Settings Creation Log:
Found settings source path at C:\Modding\SynthEBD\Settings\SettingsSource.json
Source Settings: 
Load Settings from Portable Folder: False
Portable Folder Location: 


Patcher Environment Creation Log:
Found environment source path at C:\Modding\SynthEBD\Settings\EnvironmentSource.json
Source Settings: 
Skyrim Version: SkyrimSE
Game Environment Directory: C:\Games\steamapps\common\Skyrim Special Edition\Data
```

If I disable asset pack distribution, the crash doesn't occur.

**Comment by Piranha91** [comment]
@matashina that's a weird one - looking at the stack trace, it shouldn't be calling the function that it's calling. I just released 0.9.3.2 which adds more detail to the crash logs - would you mind doing the following?

1. Install 0.9.3.2
2. Run the patcher
3. When it crashes, check out the name of the NPC that caused it to crash (at the end of the exception message).
4. Launch SynthEBD again and add that NPC to the "Verbose Log for Specific NPCs" list in the General Settings
5. Run the patcher again. This time, the error message should say that it wrote the verbose log 
6. Upload both the error message and the verbose log.

Thanks! I'm really interested in getting to the bottom of this one because I genuinely don't understand how it's possible - the logic flow should have prevented it from going from line 194 to line 377.

**Comment by matashina** [comment]
Hey @Piranha91, thanks as always for the tech support. It doesn't sound like you need the logs, but just in case they're helpful, here's the [verbose log for the crashing NPC](https://gist.github.com/matashina/f5d3e20c1b659fd92397108a4dc7cc9b) and [the crash log.](https://gist.github.com/matashina/91323c4a39ebf031bb35874047b32690)

**Comment by matashina** [comment]
Oh, hmm. No crashes if I turn consistency off...!

**Comment by Gawdzila** [comment]
Oh wow, excellent discovery matashina!  I can also run it with consistency off.  Good thing too, because apparently I can't run the 0.8.5 patcher anymore because of licensing or somesuch, lol.

**Comment by Piranha91** [comment]
Alright, can you you guys check if you still have the issue with consistency in 0.9.4?

**Comment by Gawdzila** [comment]
Bada bing!  Fixed for me! :)

**Comment by matashina** [comment]
Sorry for the late response! Yes, 0.9.4 fixed it for me as well. Thank you so much, Piranha!
